### ISSUE TITLE
Always #include specifics first before system includes

### ISSUE THREAD

**Issue by deanagan** [Hydroleks/TriviaGame#1]
https://github.com/Hydroleks/TriviaGame/blob/f0d8874b0ceec5d5b01cfb5fb7068f362fc18221/TriviaGame/TriviaGame.cpp#L5

Make it a habit to put header files in inclusion first.

See here: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Comment by leksandar-stojanovic** [comment]
Cheers for the info. Will try and follow this.
