### ISSUE TITLE
Prefer make_unique

### ISSUE THREAD

**Issue by deanagan** [Hydroleks/TriviaGame#3]
https://github.com/Hydroleks/TriviaGame/blob/f0d8874b0ceec5d5b01cfb5fb7068f362fc18221/TriviaGame/TriviaFactory.cpp#L27

If you are using C++14 and later, prefer 
return std::make_unique<AbstractBaseClass>(args); over returning a unique_ptr.

If you are using C++11,  this should be:
return std::unique_ptr<AbstractBaseClass>(new ConcreteClass{});

**Comment by leksandar-stojanovic** [comment]
Quickly skimed over this one. make_unique seems a bit safer and is better at handling exception during object creation.
