### ISSUE TITLE
Redundant parent call

### ISSUE THREAD

**Issue by deanagan** [Hydroleks/TriviaGame#5]
https://github.com/Hydroleks/TriviaGame/blob/f0d8874b0ceec5d5b01cfb5fb7068f362fc18221/TriviaGame/Game/MultiChoice.cpp#L8

The parent constructor doesn't need to be explicitly called. Although, I do have to mention that some linters like pclint forces us to call the super constructor, I would go with clang-tidy telling us not to because it is redundant.

**Comment by leksandar-stojanovic** [comment]
Removed redundant calls.
